{% set name = "panacota" %}
{% set version = "1.0.1.post2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9e5210b5d5360400de4a9e9dfecfa871b4493bfa891c3474c31f5d538e4744f4

build:
  noarch: python
  number: 0
  entry_points:
    - PanACoTA=PanACoTA.bin.run_panacota:main
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv ."

requirements:
  host:
    - python>=3.4
    - pip
  run:
    - python>=3.4
    - argparse
    - biopython >=1.60
    - colorlog
    - matplotlib-base >=2.0.0
    - ncbi-genome-download >=0.3.0
    - numpy >=1.11
    - progressbar2 >=3.18.0
    - scipy
    - termcolor
    - mash
    - prodigal >=2.6.2
    - prokka >=1.11, <=1.14.5
    - mmseqs2
    - mafft
    - iqtree >=1.6.12
    - fasttree >=2.1.10
    - quicktree
    - fastme

test:
  imports:
    - panacota
  commands:
    - PanACoTA --help

about:
  home: "https://github.com/gem-pasteur/PanACoTA"
  license: GNU Affero General Public v3
  license_family: AGPL
  license_file: COPYING
  summary: "Large scale comparative genomics tools: annotate genomes, do pangenome, core/persistent genome, align core/persistent families, infer phylogenetic tree."
  doc_url: "https://aperrin.pages.pasteur.fr/pipeline_annotation/html-doc/"
  dev_url: "https://github.com/gem-pasteur/PanACoTA"
